apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: order-saga
build:
  artifacts:
  - image: dev.local/order-saga
    jib: {}
manifests:
  kustomize:
    paths:
    - k8s
deploy:
  kubectl: {}
