apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: product-saga
build:
  artifacts:
  - image: dev.local/product-saga
    jib: {}
manifests:
  kustomize:
    paths:
    - k8s
deploy:
  kubectl: {}
